### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by EmilRyberg** [IntelligentRoboticsLabs/marathon_ros2#2]
Hi.

Is it possible that you can add a license to the repository?
I want to be able to fork it, to update minor things for ros2 foxy :slightly_smiling_face:

**Comment by fmrico** [comment]
Hi @EmilRyberg 

I have just added the license in #3. Thanks to point this.

@jginesclavero @lbajo There are still some TODOs in the description in `package.xml` files. Maybe you could write a sentence or two to describe the purpose of the package.
